name: style

on:
  push: {branches: [main]} # pushes to main
  pull_request: {} # all PRs

jobs:
  ruff:
    strategy:
      matrix:
        python-version: ['3.10']
        os: ['ubuntu-latest']
        pyserini: ['pyserini']
        pyterrier: [
          'git+https://github.com/terrier-org/pyterrier@remove_anserini', # TMP: remove_anserini branch
        ]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip install --upgrade -r requirements.txt -r requirements-dev.txt faiss-cpu torch
        pip uninstall -y python-terrier pyserini
        pip install --upgrade ${{ matrix.pyterrier }} ${{ matrix.pyserini }} # use the specified pyterrier and pyserini versions
        pip install .

    - name: Cache Dependencies
       uses: actions/cache@v4
       with:
         path: ${{ env.pythonLocation }}
         key: ${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.pyserini }}-${{ matrix.pyterrier }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}

    - name: Ruff
      run: 'ruff --output-format=github pyterrier_anserini'
